// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240229194212_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Cup",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/1_super_mario.jpg",
                            Name = "Super Mario Cup",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/2_no_internet.jpg",
                            Name = "T-Shirt No Internet",
                            Price = 49.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Lamp",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/3_vader.jpg",
                            Name = "Vader Lamp",
                            Price = 139.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Collection",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/4_storm_tropper.jpg",
                            Name = "Storm Tropper",
                            Price = 339.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/5_100_gamer.jpg",
                            Name = "100% Gamer",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/6_spacex.jpg",
                            Name = "SpaceX",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/7_coffee.jpg",
                            Name = "Coffee",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/8_moletom_cobra_kay.jpg",
                            Name = "Cobra Kay",
                            Price = 99.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Book",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/9_neil.jpg",
                            Name = "Star Talk",
                            Price = 59.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Play",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/10_milennium_falcon.jpg",
                            Name = "Millenium Falcon",
                            Price = 539.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/11_mars.jpg",
                            Name = "Mars",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/12_gnu_linux.jpg",
                            Name = "GNU LINUX",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "T-Shirt",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/13_dragon_ball.jpg",
                            Name = "Dragon Ball",
                            Price = 39.9m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "Patch",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut et massa non erat fringilla accumsan.",
                            ImageUrl = "https://github.com/ivanclay/GeekShopping/blob/main/images/14_patch_nasa.jpg",
                            Name = "NASA",
                            Price = 19.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
